app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'DashboardController@index');

Route::get('home', 'DashboardController@index');

Route::controllers([
	'lang' => 'LangController',
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::resource('users', 'UsersController');
Route::resource('roles', 'RolesController');
Route::resource('clients', 'ClientsController');
Route::resource('clients.printers', 'ClientPrinterController');
Route::resource('clients.invoices', 'ClientInvoicesController', ['only' => 'store']);
Route::resource('permissions', 'PermissionsController');

Route::resource('invoices', 'InvoicesController');
Route::get('invoices/{invoices}/download', ['as' => 'invoices.download', 'uses' => 'InvoicesController@download']);

Route::group(['prefix' => 'api'], function()
{
	Route::resource('invoices', 'Api\InvoicesController');
	Route::resource('invoiced-products', 'Api\InvoicedProductsController', ['only' => ['store', 'update', 'destroy']]);
	Route::resource('printers', 'Api\PrintersController');
	Route::resource('products', 'Api\ProductsController');
});

resources/views/partials/errors.blade.php
@if (count($errors) > 0)
	<div class="alert alert-danger">
		<strong>@lang('partials.whoops')</strong> @lang('partials.problems_with_input')<br><br>

		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

			<a class="navbar-brand" href="{{ url() }}">{{ env('APP_NAME') }}</a>
		</div>

		<div class="collapse navbar-collapse" id="navbar">
			@if (Auth::check())
				<ul class="nav navbar-nav">
					<li>
						<a href="{{ url() }}">@lang('partials.dashboard')</a>
					</li>

					@if (is_master())
						<li>
							<a href="{{ route('roles.index') }}">@lang('partials.roles')</a>
						</li>

						<li>
							<a href="{{ route('permissions.index') }}">@lang('partials.permissions')</a>
						</li>

						<li>
							<a href="{{ route('users.index') }}">@lang('partials.users')</a>
						</li>

						<li>
							<a href="{{ route('clients.index') }}">@lang('partials.clients')</a>
						</li>
					@endif

					@if (is_allowed('invoices.index'))
						<li>
							<a href="{{ route('invoices.index') }}">@lang('partials.invoices')</a>
						</li>
					@endif
				</ul>
			@endif

			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						@lang('partials.languages') <span class="caret"></span>
					</a>

					<ul class="dropdown-menu">
						@foreach (trans('languages') as $lang => $language)
							<li>
								<a href="{{ url('lang/change', $lang) }}">{{ $language }}</a>
							</li>
						@endforeach
					</ul>
				</li>

				@if (Auth::check())
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							{{ Auth::user()->name }} <span class="caret"></span>
						</a>

						<ul class="dropdown-menu">
							<li>
								<a href="{{ url('auth/logout') }}">@lang('partials.logout')</a>
							</li>
						</ul>
					</li>
				@endif
			</ul>
		</div>
	</div>
</nav>