app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'DashboardController@index');

Route::get('home', 'DashboardController@index');

Route::controllers([
	'lang' => 'LangController',
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::resource('users', 'UsersController');
Route::resource('roles', 'RolesController');
Route::resource('clients', 'ClientsController');
Route::resource('clients.printers', 'ClientPrinterController');
Route::resource('clients.invoices', 'ClientInvoicesController', ['only' => 'store']);
Route::resource('permissions', 'PermissionsController');

Route::resource('invoices', 'InvoicesController');
Route::get('invoices/{invoices}/download', ['as' => 'invoices.download', 'uses' => 'InvoicesController@download']);

Route::group(['prefix' => 'api'], function()
{
	Route::resource('invoices', 'Api\InvoicesController');
	Route::resource('invoiced-products', 'Api\InvoicedProductsController', ['only' => ['store', 'update', 'destroy']]);
	Route::resource('printers', 'Api\PrintersController');
	Route::resource('products', 'Api\ProductsController');
});

app/Client.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model {

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name'];

	/**
	 * Client has many printers.
	 *
	 * @return BelongsToMany
	 */
	public function printers()
	{
		return $this->belongsToMany('App\Printer')->withPivot('quantity');
	}

	/**
	 * Client has many invoices.
	 *
	 * @return HasMany
	 */
	public function invoices()
	{
		return $this->hasMany('App\Invoice');
	}

}

app/Http/Controllers/ClientsController.php
<?php namespace App\Http\Controllers;

use App\Client;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateClientRequest;

class ClientsController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');

		$this->middleware('master');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$clients = Client::orderBy('name')->paginate();

		return view('clients.index', compact('clients'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('clients.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateClientRequest $request)
	{
		Client::create($request->all());

		return redirect()->route('clients.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$client = Client::findOrFail($id);

		return view('clients.show', compact('client'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$client = Client::findOrFail($id);

		return view('clients.edit', compact('client'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(CreateClientRequest $request, $id)
	{
		Client::findOrFail($id)->update($request->all());

		return redirect()->route('clients.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$client = Client::findOrFail($id);

		$client->delete();

		return redirect()->route('clients.index');
	}

}

resources/views/clients/create.blade.php
@extends('layouts.form')

@section('form.content')
	<div class="panel panel-default">
		<div class="panel-heading">@lang('clients.create_client')</div>

		<div class="panel-body">
			@include('partials.errors')

			{!! Form::open(['url' => route('clients.store'), 'method' => 'post', 'class' => 'form-horizontal']) !!}
				@include('clients.form')

				<div class="form-group">
					<div class="col-md-offset-3 col-md-6">
						<button type="submit" class="btn btn-success">@lang('clients.create')</button>
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.form')

@section('form.content')
	<div class="panel panel-default">
		<div class="panel-heading">@lang('clients.edit_client')</div>

		<div class="panel-body">
			@include('partials.errors')

			{!! Form::model($client, ['url' => route('clients.update', $client), 'method' => 'put', 'class' => 'form-horizontal']) !!}
				@include('clients.form')

				<div class="form-group">
					<div class="col-md-offset-3 col-md-6">
						<button type="submit" class="btn btn-success">@lang('clients.update')</button>
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">@lang('clients.delete_client')</div>

		<div class="panel-body">
			{!! Form::open(['url' => route('clients.destroy', $client->id), 'method' => 'delete', 'class' => 'form-horizontal']) !!}
				<div class="form-group">
					<label class="col-md-3 control-label">@lang('clients.delete_client')</label>

					<div class="col-md-6">
						<button type="submit" class="btn btn-danger">@lang('clients.delete')</button>
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/clients/form.blade.php
<div class="form-group">
	<label class="col-md-3 control-label">@lang('clients.name')</label>

	<div class="col-md-6">
		{!! Form::text('name', null, ['class' => 'form-control']) !!}
	</div>
</div>

resources/views/clients/index.blade.php
@extends('app')

@section('content')
	<div class="container">
		<div class="panel panel-default">
			<div class="panel-heading">@lang('clients.clients')</div>

			<div class="list-group">
				@foreach ($clients as $client)
					<a class="list-group-item" href="{{ route('clients.show', $client->id) }}">
						<h4>{{ $client->name }}</h4>
					</a>
				@endforeach
			</div>

			<div class="panel-footer">
				<a href="{{ route('clients.create') }}" class="btn btn-primary">@lang('clients.create')</a>
			</div>
		</div>

		{!! $clients->render() !!}
	</div>
@stop

resources/views/clients/show.blade.php
@extends('app')

@section('modal')
	<div class="modal fade" id="addPrinterModal">
		<div class="modal-dialog">
			<div class="modal-content">
				{!! Form::open(['route' => ['clients.printers.store', $client->id], 'method' => 'post']) !!}
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">Add new printer</h4>
					</div>

					<div class="modal-body">
						<div class="form-group">
							<label>Printer name</label>
							<select selectize name="printer_id" value-field="id" label-field="full_name" remote="{{ route('api.printers.index') }}"></select>
						</div>

						<div class="form-group">
							<label>Quantity</label>
							<input type="number" name="quantity" value="1" min="1" class="form-control">
						</div>
					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="submit" class="btn btn-primary">Add</button>
					</div>
				{!! Form::close() !!}
			</div>
		</div>
	</div>
@stop

@section('content')
	<div class="container">
		<div class="panel panel-default">
			<div class="panel-heading">@lang('clients.clients')</div>

			<div class="panel-body">
				<h4>{{ $client->name }}</h4>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">Invoices</div>

				<div class="table-responsive">
					<table class="table table-hover">
						<thead>
							<tr>
								<th>@lang('invoices.code')</th>
								<th>Price</th>
								<th>Invoice Date</th>
								<th>@lang('invoices.created_by')</th>
								<th>Status</th>
								<th></th>
							</tr>
						</thead>

						<tbody>
							@forelse ($client->invoices as $invoice)
								<tr>
									<td>
										<a href="{{ route('invoices.show', $invoice->id) }}">{{ $invoice->code }}</a>
									</td>

									<td>{{ amount($invoice->price) }}</td>
									<td>{{ $invoice->created_on }}</td>
									<td>{{ $invoice->creator->name }}</td>
									<td>{{ ucfirst($invoice->status) }}</td>
									<td class="text-right">
										@if ($invoice->status == 'draft')
											<a class="btn btn-xs btn-warning" href="{{ route('invoices.edit', $invoice->id) }}">Edit</a>
										@endif

										<a class="btn btn-xs btn-success" href="{{ route('invoices.download', $invoice->id) }}">Download</a>
									</td>
								</tr>
							@empty
								<tr>
									<td class="text-muted" colspan="100%">@lang('invoices.no_invoices')</td>
								</tr>
							@endforelse
						</tbody>
					</table>
				</div>

				<div class="panel-footer">
					{!! Form::open(['route' => ['clients.invoices.store', $client->id]]) !!}
						{!! Form::submit('New Invoice', ['class' => 'btn btn-primary']) !!}
					{!! Form::close() !!}
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">@lang('clients.printers')</div>

				<ul class="list-group">
					@foreach ($client->printers as $printer)
						<li class="list-group-item">
							<span class="badge">{{ $printer->pivot->quantity }}</span>
							<h4 class="list-group-item-heading">{{ $printer->full_name }}</h4>

							<p class="list-group-item-text">
								{!! Form::open(['route' => ['clients.printers.destroy', $client->id, $printer->id], 'method' => 'delete']) !!}
									<button type="submit" class="btn btn-danger btn-xs">@lang('clients.remove')</button>
								{!! Form::close() !!}
							</p>
						</li>
					@endforeach
				</ul>

				<div class="panel-footer">
					<button class="btn btn-primary" data-toggle="modal" data-target="#addPrinterModal">@lang('clients.add')</button>
				</div>
			</div>
		</div>
	</div>
@stop