app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'DashboardController@index');

Route::get('home', 'DashboardController@index');

Route::controllers([
	'lang' => 'LangController',
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::resource('users', 'UsersController');
Route::resource('roles', 'RolesController');
Route::resource('clients', 'ClientsController');
Route::resource('clients.printers', 'ClientPrinterController');
Route::resource('clients.invoices', 'ClientInvoicesController', ['only' => 'store']);
Route::resource('permissions', 'PermissionsController');

Route::resource('invoices', 'InvoicesController');
Route::get('invoices/{invoices}/download', ['as' => 'invoices.download', 'uses' => 'InvoicesController@download']);

Route::group(['prefix' => 'api'], function()
{
	Route::resource('invoices', 'Api\InvoicesController');
	Route::resource('invoiced-products', 'Api\InvoicedProductsController', ['only' => ['store', 'update', 'destroy']]);
	Route::resource('printers', 'Api\PrintersController');
	Route::resource('products', 'Api\ProductsController');
});

app/Role.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model {

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'description'];

	public function permissions()
	{
		return $this->hasMany('App\Permission');
	}

	public function users()
	{
		return $this->hasMany('App\User');
	}

	public function hasPermission($route)
	{
		foreach ($this->permissions as $permission)
		{
			if (str_is($permission->route, $route))
			{
				return true;
			}
		}

		return false;
	}

}

app/Http/Controllers/RolesController.php
<?php namespace App\Http\Controllers;

use App\Role;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateRoleRequest;

class RolesController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');

		$this->middleware('master');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$roles = Role::orderBy('name')->paginate();

		return view('roles.index', compact('roles'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('roles.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateRoleRequest $request)
	{
		Role::create($request->all());

		return redirect()->route('roles.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$role = Role::findOrFail($id);

		return view('roles.edit', compact('role'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(CreateRoleRequest $request, $id)
	{
		Role::findOrFail($id)->update($request->all());

		return redirect()->route('roles.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$role = Role::findOrFail($id);

		$role->permissions()->delete();

		$role->users()->delete();

		$role->delete();

		return redirect()->route('roles.index');
	}

}

resources/views/roles/create.blade.php
@extends('layouts.form')

@section('form.content')
	<div class="panel panel-default">
		<div class="panel-heading">@lang('roles.create_role')</div>

		<div class="panel-body">
			@include('partials.errors')

			{!! Form::open(['url' => route('roles.store'), 'method' => 'post', 'class' => 'form-horizontal']) !!}
				@include('roles.form')

				<div class="form-group">
					<div class="col-md-offset-3 col-md-6">
						<button type="submit" class="btn btn-success">@lang('roles.create')</button>
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.form')

@section('form.content')
	<div class="panel panel-default">
		<div class="panel-heading">@lang('roles.edit_role')</div>

		<div class="panel-body">
			@include('partials.errors')

			{!! Form::model($role, ['url' => route('roles.update', $role), 'method' => 'put', 'class' => 'form-horizontal']) !!}
				@include('roles.form')

				<div class="form-group">
					<div class="col-md-offset-3 col-md-6">
						<button type="submit" class="btn btn-success">@lang('roles.update')</button>
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">@lang('roles.delete_role')</div>

		<div class="panel-body">
			{!! Form::open(['url' => route('roles.destroy', $role->id), 'method' => 'delete', 'class' => 'form-horizontal']) !!}
				<div class="form-group">
					<label class="col-md-3 control-label">@lang('roles.delete_role')</label>

					<div class="col-md-6">
						<button type="submit" class="btn btn-danger">@lang('roles.delete')</button>
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/roles/form.blade.php
<div class="form-group">
	<label class="col-md-3 control-label">@lang('roles.name')</label>

	<div class="col-md-6">
		{!! Form::text('name', null, ['class' => 'form-control']) !!}
	</div>
</div>

<div class="form-group">
	<label class="col-md-3 control-label">@lang('roles.description')</label>

	<div class="col-md-6">
		{!! Form::text('description', null, ['class' => 'form-control']) !!}
	</div>
</div>

resources/views/roles/index.blade.php
@extends('app')

@section('content')
	<div class="container">
		<div class="panel panel-default">
			<div class="panel-heading">@lang('roles.roles')</div>

			<ul class="list-group">
				@foreach ($roles as $role)
					<li class="list-group-item">
						<span class="pull-right">
							<a href="{{ route('roles.edit', $role->id) }}" class="btn btn-warning">@lang('roles.edit')</a>
						</span>

						<h4 class="list-group-item-heading">{{ $role->name }}</h4>

						<p class="list-group-item-text text-muted">
							{{ empty($role->description) ? 'No description' : $role->description }}
						</p>
					</li>
				@endforeach
			</ul>

			<div class="panel-footer">
				<a href="{{ route('roles.create') }}" class="btn btn-primary">@lang('roles.create')</a>
			</div>
		</div>

		{!! $roles->render() !!}
	</div>
@stop